/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResponsavelRouteImport } from './routes/responsavel'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'

const ResponsavelRoute = ResponsavelRouteImport.update({
  id: '/responsavel',
  path: '/responsavel',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/checkin': typeof CheckinRoute
  '/equipe': typeof EquipeRoute
  '/painel': typeof PainelRoute
  '/responsavel': typeof ResponsavelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/checkin': typeof CheckinRoute
  '/equipe': typeof EquipeRoute
  '/painel': typeof PainelRoute
  '/responsavel': typeof ResponsavelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/checkin': typeof CheckinRoute
  '/equipe': typeof EquipeRoute
  '/painel': typeof PainelRoute
  '/responsavel': typeof ResponsavelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/checkin'
    | '/equipe'
    | '/painel'
    | '/responsavel'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cadastro' | '/checkin' | '/equipe' | '/painel' | '/responsavel'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/checkin'
    | '/equipe'
    | '/painel'
    | '/responsavel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  CheckinRoute: typeof CheckinRoute
  EquipeRoute: typeof EquipeRoute
  PainelRoute: typeof PainelRoute
  ResponsavelRoute: typeof ResponsavelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/responsavel': {
      id: '/responsavel'
      path: '/responsavel'
      fullPath: '/responsavel'
      preLoaderRoute: typeof ResponsavelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  CheckinRoute: CheckinRoute,
  EquipeRoute: EquipeRoute,
  PainelRoute: PainelRoute,
  ResponsavelRoute: ResponsavelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
