/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EquipeRouteImport } from './routes/equipe'

const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/equipe': typeof EquipeRoute
}
export interface FileRoutesByTo {
  '/equipe': typeof EquipeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/equipe': typeof EquipeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/equipe'
  fileRoutesByTo: FileRoutesByTo
  to: '/equipe'
  id: '__root__' | '/equipe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  EquipeRoute: typeof EquipeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  EquipeRoute: EquipeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
